import{i as b,S}from"./assets/vendor-5b791d57.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const o of t.addedNodes)o.tagName==="LINK"&&o.rel==="modulepreload"&&i(o)}).observe(document,{childList:!0,subtree:!0});function c(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function i(e){if(e.ep)return;e.ep=!0;const t=c(e);fetch(e.href,t)}})();const x="/goit-js-hw-11/assets/bi_x-octagon-42c005e5.svg",P={BASE_URL:"https://pixabay.com",END_POINT:"/api/",API_KEY:"42307570-a64cb029cc8427df0f0b3ddcd",constParameters:"&image_type=photo&orientation=horizontal&safesearch=true"},n={renderMarkup(s){document.querySelector(".gallery").innerHTML=s},removeMarkup(){document.querySelector(".gallery").innerHTML=""},setLoader(){document.querySelector(".gallery").insertAdjacentHTML("beforebegin",'<span class="loader"></span>')},removeLoader(){document.querySelector(".loader").remove()}},l=document.querySelector(".form");l.addEventListener("submit",$);function $(s){s.preventDefault(),n.removeMarkup();const r=s.target.elements.searchInput.value;if(l.reset(),r){n.setLoader();const{BASE_URL:c,END_POINT:i,API_KEY:e,constParameters:t}=P,o=`${c}${i}?key=${e}&q=${r}${t}`;fetch(o).then(a=>a.json()).then(a=>{if(a.hits.length===0){b.error({timeout:3e3,message:"Sorry, there are no images matching your search query. Please try again!",maxWidth:"432px",messageColor:"#fff",messageSize:"16px",messageLineHeight:"1.5",backgroundColor:"#ef4040",position:"topRight",titleColor:"#fff",titleSize:"16px",titleLineHeight:"1.5",iconUrl:x});return}else{const d=a.hits.map(u=>{const{webformatURL:f,largeImageURL:p,tags:g,likes:h,views:v,comments:y,downloads:L}=u;return`<li class="gallery-item">
<a class="gallery-link" href=${p}>
<img class="gallery-image" src=${f} alt="${g}" />
</a><div class="options-div"><div class="item-div"><h4 class="item-div-name">Likes</h4>
  <p class="item-div-text">${h}</p></div><div class="item-div"><h4 class="item-div-name">Views</h4>
  <p class="item-div-text">${v}</p></div><div class="item-div"><h4 class="item-div-name">Comments</h4>
  <p class="item-div-text">${y}</p></div><div class="item-div"><h4 class="item-div-name">Downloads</h4>
  <p class="item-div-text">${L}</p></div></div>
</li>`}).join("");n.renderMarkup(d);var m=new S(".gallery a",{captionPosition:"bottom",captionsData:"alt",className:"modal"});m.refresh()}}).catch(()=>{console.log("Mistake from server")}),setTimeout(()=>{n.removeLoader()},1e3)}}
//# sourceMappingURL=commonHelpers.js.map
