import{i as g,S as h}from"./assets/vendor-5b791d57.js";(function(){const i=document.createElement("link").relList;if(i&&i.supports&&i.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const r of t.addedNodes)r.tagName==="LINK"&&r.rel==="modulepreload"&&s(r)}).observe(document,{childList:!0,subtree:!0});function a(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function s(e){if(e.ep)return;e.ep=!0;const t=a(e);fetch(e.href,t)}})();const v="/goit-js-hw-11/assets/bi_x-octagon-42c005e5.svg",n=document.querySelector(".form");n.addEventListener("submit",y);function y(o){o.preventDefault(),document.querySelector(".gallery").insertAdjacentHTML("beforebegin",'<span class="loader"></span>');const i=o.target.elements.searchInput.value;if(n.reset(),i){const a=`https://pixabay.com/api/?key=42307570-a64cb029cc8427df0f0b3ddcd&q=${i}&image_type=photo&orientation=horizontal&safesearch=true`;document.querySelector(".gallery").innerHTML="",fetch(a).then(s=>s.json()).then(s=>{if(s.hits.length===0){g.error({timeout:3e3,message:"Sorry, there are no images matching your search query. Please try again!",maxWidth:"432px",messageColor:"#fff",messageSize:"16px",messageLineHeight:"1.5",backgroundColor:"#ef4040",position:"topRight",titleColor:"#fff",titleSize:"16px",titleLineHeight:"1.5",iconUrl:v});return}else{const t=s.hits.map(r=>{const{webformatURL:c,largeImageURL:l,tags:m,likes:d,views:u,comments:f,downloads:p}=r;return`<li class="gallery-item">
<a class="gallery-link" href=${l}>
<img class="gallery-image" src=${c} alt="${m}" />
</a><div class="options-div"><div class="item-div"><h4 class="item-div-name">Likes</h4>
  <p class="item-div-text">${d}</p></div><div class="item-div"><h4 class="item-div-name">Views</h4>
  <p class="item-div-text">${u}</p></div><div class="item-div"><h4 class="item-div-name">Comments</h4>
  <p class="item-div-text">${f}</p></div><div class="item-div"><h4 class="item-div-name">Downloads</h4>
  <p class="item-div-text">${p}</p></div></div>
</li>`}).join("");document.querySelector(".gallery").innerHTML=t;var e=new h(".gallery a",{captionPosition:"bottom",captionsData:"alt",className:"modal"});e.refresh()}}).catch(()=>{console.log("Mistake from server")}),setTimeout(()=>{document.querySelector(".loader").remove()},1e3)}}
//# sourceMappingURL=commonHelpers.js.map
