import{i as L,S as b}from"./assets/vendor-5b791d57.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&o(i)}).observe(document,{childList:!0,subtree:!0});function n(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function o(e){if(e.ep)return;e.ep=!0;const t=n(e);fetch(e.href,t)}})();const S="/goit-js-hw-11/assets/bi_x-octagon-42c005e5.svg",x={BASE_URL:"https://pixabay.com",END_POINT:"/api/",API_KEY:"42307570-a64cb029cc8427df0f0b3ddcd",constParameters:"&image_type=photo&orientation=horizontal&safesearch=true"};function P(r){document.querySelector(".gallery").innerHTML=r}const c=document.querySelector(".form");c.addEventListener("submit",$);function $(r){r.preventDefault(),document.querySelector(".gallery").innerHTML="";const s=r.target.elements.searchInput.value;if(c.reset(),s){document.querySelector(".gallery").insertAdjacentHTML("beforebegin",'<span class="loader"></span>');const{BASE_URL:n,END_POINT:o,API_KEY:e,constParameters:t}=x,i=`${n}${o}?key=${e}&q=${s}${t}`;fetch(i).then(a=>a.json()).then(a=>{if(a.hits.length===0){L.error({timeout:3e3,message:"Sorry, there are no images matching your search query. Please try again!",maxWidth:"432px",messageColor:"#fff",messageSize:"16px",messageLineHeight:"1.5",backgroundColor:"#ef4040",position:"topRight",titleColor:"#fff",titleSize:"16px",titleLineHeight:"1.5",iconUrl:S});return}else{const m=a.hits.map(d=>{const{webformatURL:u,largeImageURL:f,tags:p,likes:g,views:h,comments:v,downloads:y}=d;return`<li class="gallery-item">
<a class="gallery-link" href=${f}>
<img class="gallery-image" src=${u} alt="${p}" />
</a><div class="options-div"><div class="item-div"><h4 class="item-div-name">Likes</h4>
  <p class="item-div-text">${g}</p></div><div class="item-div"><h4 class="item-div-name">Views</h4>
  <p class="item-div-text">${h}</p></div><div class="item-div"><h4 class="item-div-name">Comments</h4>
  <p class="item-div-text">${v}</p></div><div class="item-div"><h4 class="item-div-name">Downloads</h4>
  <p class="item-div-text">${y}</p></div></div>
</li>`}).join("");P(m);var l=new b(".gallery a",{captionPosition:"bottom",captionsData:"alt",className:"modal"});l.refresh()}}).catch(()=>{console.log("Mistake from server")}),setTimeout(()=>{document.querySelector(".loader").remove()},1e3)}}
//# sourceMappingURL=commonHelpers.js.map
